- name: Update all servers
  hosts: all
  tasks:
    - name: Update centos/rh
      yum: name=* state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Update Ubuntu/Debian
      apt: name=* state=latest update-cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
